version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: >
      bash -c "
        bundle exec rails db:create &&
        bundle exec rails db:migrate &&
        bundle exec rails s -b '0.0.0.0'
      "
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      IPSTACK_API_KEY: ${IPSTACK_API_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}

volumes:
  postgres_data: