version: '3'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${GEOLOCATION_PRODUCTION_USERNAME}
      POSTGRES_PASSWORD: ${GEOLOCATION_PRODUCTION_PASSWORD}
      POSTGRES_DB: geolocation
    volumes:
      - postgres_data:/var/lib/postgresql/data
  test:
    build: .
    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        bundle exec rails db:migrate &&
        bundle exec rspec
      "
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${GEOLOCATION_TEST_USERNAME}:${GEOLOCATION_TEST_PASSWORD}@host.docker.internal:5432/geolocation_test
      IPSTACK_API_KEY: ${IPSTACK_API_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
volumes:
  postgres_data: